image: eclipse-temurin:21-jdk

stages: [test]

variables:
  MAVEN_CLI_OPTS: >-
    -B -U --no-transfer-progress
    -Dmaven.repo.local=.m2/repository
    -Dsurefire.printSummary=true -Dsurefire.useFile=false

cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  policy: pull-push
  paths:
    - .m2/repository

.assignment:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - ./mvnw -v
    - ./mvnw ${MAVEN_CLI_OPTS} -P ${PROFILE} verify
  artifacts:
    when: always
    reports:
      junit: "target/surefire-reports/*${PROFILE}*.xml"
    paths:
      - target/surefire-reports/
      - target/site/jacoco/
    expire_in: 1 week

assignments:
  extends: .assignment
  parallel:
    matrix:
      - PROFILE: "a01"
        EXISTS: "src/main/java/assignments/introduction/**"
      - PROFILE: "a02"
        EXISTS: "src/main/java/assignments/figures/v1/**"

  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "teacher"'
      when: on_success
    - exists:
        - "$EXISTS"
      when: on_success
    - when: never

run-all:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
  script:
    - ./mvnw -v
    - ./mvnw ${MAVEN_CLI_OPTS} -P a01,a02 verify
  artifacts:
    when: always
    reports:
      junit: "target/surefire-reports/*.xml"
    paths:
      - target/surefire-reports/
      - target/site/jacoco/
    expire_in: 1 week
