image: eclipse-temurin:21-jdk

stages: [test]

variables:
  MAVEN_OPTS: "-DskipITs -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -U --no-transfer-progress -Dsurefire.printSummary=true -Dsurefire.useFile=false"
  TESTS_BASE: "${CI_SERVER_URL}/${CI_PROJECT_NAMESPACE}/javacore-tests/-/raw/main"

cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

.before_tools:
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends unzip
    - rm -rf /var/lib/apt/lists/*

.assignment:
  stage: test
  extends: .before_tools
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - ./mvnw -v
    - curl -fsSL --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        "$TESTS_BASE/${TEST_ARCHIVE}" -o tests.zip
    - unzip -o tests.zip -d src/test/java
    - ./mvnw ${MAVEN_CLI_OPTS} -P ${PROFILE} \
      -Dassignment.includes="${ASSIGNMENT_INCLUDES}" \
      -Dreport.suffix="${REPORT_SUFFIX}" verify
  artifacts:
    when: always
    reports:
      junit: "target/surefire-reports/*${REPORT_SUFFIX}*.xml"
    paths:
      - target/surefire-reports/
      - target/site/jacoco/
    expire_in: 1 week

assignments:
  extends: .assignment
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "teacher"'
      when: on_success
    - exists:
        - "$EXISTS"
      when: on_success
    - when: never
  parallel:
    matrix:
      - PROFILE: "a01"
        REPORT_SUFFIX: "introduction"
        ASSIGNMENT_INCLUDES: "**/introduction/**/Test**.java"
        TEST_ARCHIVE: "tests-assignment-01.zip"
        EXISTS: "src/main/java/assignments/introduction/**"
      - PROFILE: "a02"
        REPORT_SUFFIX: "figuresV1"
        ASSIGNMENT_INCLUDES: "**/figures/v1/**/Test**.java"
        TEST_ARCHIVE: "tests-assignment-02.zip"
        EXISTS: "src/main/java/assignments/figures/v1/**"