image: eclipse-temurin:21-jdk

stages: [test]

variables:
  MAVEN_OPTS: "-DskipITs"
  MAVEN_CLI_OPTS: "-B -U --no-transfer-progress -Dsurefire.printSummary=true -Dsurefire.useFile=false"

cache:
  key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

before_script:
  - dos2unix mvnw || true
  - chmod +x mvnw || true
  - ./mvnw -v || true

test:
  stage: test
  script:
    - ./mvnw ${MAVEN_CLI_OPTS} verify
  artifacts:
    when: always
    reports:
      junit: "**/target/surefire-reports/*.xml"
    paths:
      - "**/target/surefire-reports/"
      - "**/target/site/jacoco/"
    expire_in: 1 week